version: '3'
services:
  source_postgres:
    image: postgres:15 #15 to match pg_dump python version
    ports: 
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql

  destination_postgres:
    image: postgres:latest
    ports: 
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  
  elt_script: 
    build: 
      context: .
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.latest
    command: 
      [
        "run",
        "--profiles-dir",
        "/root/.dbt",
        "--project-dir",
        "/usr/app/dbt"
      ]
    networks:
      - elt_network
    volumes: 
      - ./custom_postgres:/usr/app/dbt
      - ./profiles.yml:/root/.dbt/profiles.yml
    depends_on:
      - elt_script
    environment:
      DBT_PROFILE: default
      DBT_TARGET: dev

networks:
  elt_network:
    driver: bridge