custom_postgres:
  outputs:
    dev:
      dbname: destination_db
      host: destination_postgres
      pass: secret
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev