
version: 2

models:
  - name: film_ratings
    description: "This model aggregates film data and calculates the average rating for each film."
    columns:
      - name: film_id
        description: "The unique identifier for each film."
        tests:
          - unique
          - not_null

      - name: title
        description: "The title of the film."
        tests:
          - not_null

      - name: release_date
        description: "The release date of the film."
        tests:
          - not_null

      - name: price
        description: "The price of the film."
        tests:
          - not_null

      - name: rating
        description: "The MPAA rating of the film."

      - name: user_rating
        description: "The average user rating for the film."
        tests:
          - not_null

      - name: actor_count
        description: "The number of actors in the film."
        tests:
          - not_null

      - name: avg_actor_rating
        description: "The average rating of films that the actors of this film have acted in."
        tests:
          - not_null